# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER ruoyi

# 挂载目录
VOLUME /home/ruoyi
# 创建目录
RUN mkdir -p /home/ruoyi
# 指定路径
WORKDIR /home/ruoyi
# 复制jar文件到路径
COPY ./jar/yyt-modules-job.jar /home/ruoyi/yyt-modules-job.jar
# 启动定时任务服务
ENTRYPOINT ["java","-jar","yyt-modules-job.jar"]